# These are supported funding model platforms

github: [ldenoue]
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=R9JRASMAABUUE&item_name=Yawas+Web+and+PDF+Highlighter&currency_code=USD&source=appblit']
